export default {
prisma: {
    id: 1,
    name: 'prisma',
    types: [
      'String',
      'Int',
      'Float',
      'Boolean',
      'DateTime',
      'Json',
      'Decimal',
      'BigInt',
      'Bytes',
      'Enum',
    ],
  },
  id: 2,
  sequelize: {
    name: 'sequelize',
    types: [
      'STRING',
      'CHAR',
      'TEXT',
      'INTEGER',
      'BIGINT',
      'FLOAT',
      'DOUBLE',
      'REAL',
      'BOOLEAN',
      'DATE',
      'DATEONLY',
      'TIME',
      'UUID',
      'UUIDV1',
      'UUIDV4',
      'NOW',
      'ENUM',
      'ARRAY',
      'JSON',
      'JSONB',
      'BLOB',
      'DECIMAL',
      'DECIMAL(10, 2)',
    ],
  },
  mongoose: {
    id: 3,
    name: 'mongoose',
    types: [
      'String',
      'Number',
      'Date',
      'Buffer',
      'Boolean',
      'Mixed',
      'ObjectId',
      'Array',
      'Decimal128',
      'Map',
      'Schema.Types.ObjectId',
      'Schema.Types.Mixed',
      'Schema.Types.Buffer',
      'Schema.Types.Decimal128',
      'Schema.Types.Map',
    ],
  },
  typeORM: {
    id: 4,
    name: 'typeORM',
    types: [
      'String',
      'Number',
      'Boolean',
      'Date',
      'Buffer',
      'ObjectID',
      'ObjectId',
      'Object',
      'Array',
      'Enum',
      'Json',
      'Number[]',
      'String[]',
      'Boolean[]',
      'Date[]',
      'Buffer[]',
      'ObjectID[]',
      'ObjectId[]',
      'Object[]',
      'Enum[]',
      'Json[]',
    ],
  }
}