import { Injectable, signal } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class StoreService {
  dataStore: any = signal([
    {
      project_name: 'tasks-management-system',
      project_description: 'test project',
      orm: 'sequelize',
      database: 'mysql',
      schema: {
        users: [
          {
            name: 'username',
            type: 'STRING',
            size: '',
            defaultValue: '',
            primaryKey: false,
            allowNulls: false,
            unique: false,
            autoIncrement: false,
            foreignKey: false,
            add_another: false,
          },
          {
            name: 'email',
            type: 'STRING',
            size: '',
            defaultValue: '',
            primaryKey: false,
            allowNulls: false,
            unique: true,
            autoIncrement: false,
            foreignKey: false,
            add_another: false,
          },
          {
            name: 'password',
            type: 'STRING',
            size: '',
            defaultValue: '',
            primaryKey: false,
            allowNulls: false,
            unique: false,
            autoIncrement: false,
            foreignKey: false,
            add_another: false,
          },
        ],
        tasks: [
          {
            name: 'title',
            type: 'STRING',
            size: '',
            defaultValue: '',
            primaryKey: false,
            allowNulls: false,
            unique: false,
            autoIncrement: false,
            foreignKey: false,
            add_another: false,
          },
          {
            name: 'description',
            type: 'TEXT',
            defaultValue: '',
            primaryKey: false,
            allowNulls: true,
            unique: false,
            autoIncrement: false,
            foreignKey: false,
            add_another: false,
          },
          {
            name: 'status',
            type: 'STRING',
            size: '',
            defaultValue: 'pending',
            primaryKey: false,
            allowNulls: false,
            unique: false,
            autoIncrement: false,
            foreignKey: false,
            add_another: false,
          },
          {
            name: 'priority',
            type: 'STRING',
            size: '',
            defaultValue: 'medium',
            primaryKey: false,
            allowNulls: false,
            unique: false,
            autoIncrement: false,
            foreignKey: false,
            add_another: false,
          },
          {
            name: 'due_date',
            type: 'DATE',
            defaultValue: '',
            primaryKey: false,
            allowNulls: true,
            unique: false,
            autoIncrement: false,
            foreignKey: false,
            add_another: false,
          },
          {
            name: 'user_id',
            type: 'INTEGER',
            defaultValue: '',
            primaryKey: false,
            allowNulls: false,
            unique: false,
            autoIncrement: false,
            foreignKey: true,
            refTable: 'users',
            refField: 'id',
            relationshipType: 'Many-to-One',
            add_another: false,
          },
          {
            name: 'project_id',
            type: 'INTEGER',
            defaultValue: '',
            primaryKey: false,
            allowNulls: false,
            unique: false,
            autoIncrement: false,
            foreignKey: true,
            refTable: 'projects',
            refField: 'id',
            relationshipType: 'Many-to-One',
            add_another: false,
          },
        ],
        projects: [
          {
            name: 'name',
            type: 'STRING',
            size: '',
            defaultValue: '',
            primaryKey: false,
            allowNulls: false,
            unique: false,
            autoIncrement: false,
            foreignKey: false,
            add_another: false,
          },
          {
            name: 'description',
            type: 'TEXT',
            defaultValue: '',
            primaryKey: false,
            allowNulls: true,
            unique: false,
            autoIncrement: false,
            foreignKey: false,
            add_another: false,
          },
          {
            name: 'status',
            type: 'STRING',
            size: '',
            defaultValue: 'active',
            primaryKey: false,
            allowNulls: false,
            unique: false,
            autoIncrement: false,
            foreignKey: false,
            add_another: false,
          },
        ],
      }
    },
  ]);
  constructor() {}
}
